#!/usr/bin/env python
import readline

readline_settings = [
    'set editing-mode vi',
    'set convert-meta on',
    '"\e[A": history-search-backward',
    '"\e[B": history-search-forward'
]
#map(lambda x: readline.parse_and_bind(x), readline_settings)
for s in readline_settings:
    readline.parse_and_bind(s)

$XONSH_HISTORY_SIZE = 100000
$PROMPT = '{BOLD_GREEN}{user}@{hostname}{BOLD_BLUE} {cwd}{branch_color}{curr_branch} \n{BOLD_BLUE}${NO_COLOR} '

